export const listOfTitles = [
    'undefined is not a function',
    "He's dead jim",
    'Stay awhile and listen..',
    'post tenebras lux!',
    'Please stand by',
    'Undecided Blog Name',
    'Hailing Frequencies open',
    'Hi steve did you bring me a pizza',
    'KHAAAAAAAAAN!',
    " I'm a programmer, not an escalator.",
    'make it so!',
    'engage!',
    'There are four lights!',
    'PARKOUR!',
    'Type your text here..',
    'Smeagol hates nasty hobbitses!',
    'Ignore this title',
    'Their taking the hobbits to isengard',
];
